In [0]:
import pandas as pd
import numpy as np

In [0]:
df=pd.read_csv("Handling_Missing_Values.csv")

In [3]:
df

A     B     C     D
0  10.0  20.0  30.0  40.0
1   1.0   2.0   NaN   NaN
2   5.0   6.0   NaN   8.0
3   0.0  11.0  12.0   NaN

In [11]:
df=pd.read_csv("Handling_Missing_Values.csv")
df.dropna(axis=0,inplace=True)
df

A     B     C     D
0  10.0  20.0  30.0  40.0

In [15]:
df=pd.read_csv("Handling_Missing_Values.csv")
df.dropna(axis=1,inplace=True)
df

A     B
0  10.0  20.0
1   1.0   2.0
2   5.0   6.0
3   0.0  11.0

In [17]:
df=pd.read_csv("Handling_Missing_Values.csv")
df.dropna(how="all",inplace=True)
df

A     B     C     D
0  10.0  20.0  30.0  40.0
1   1.0   2.0   NaN   NaN
2   5.0   6.0   NaN   8.0
3   0.0  11.0  12.0   NaN

In [0]:
df=pd.read_csv("Handling_Missing_Values.csv")
df.dropna(thresh=2,inplace=True)

In [7]:
df

A     B     C     D
0  10.0  20.0  30.0  40.0
1   1.0   2.0   NaN   NaN
2   5.0   6.0   NaN   8.0
3   0.0  11.0  12.0   NaN

In [0]:
df=pd.read_csv("Handling_Missing_Values.csv")
df.dropna(subset=['C'])
df

#Imputer


In [19]:
df=pd.read_csv("Handling_Missing_Values.csv")
from sklearn.impute import SimpleImputer
imr=SimpleImputer(missing_values=np.nan, strategy='mean') #Strategy can be also median
imr=imr.fit(df)
imputed_data=imr.transform(df.values)
print(imputed_data)

[[10. 20. 30. 40.]
 [ 1.  2. 21. 24.]
 [ 5.  6. 21.  8.]
 [ 0. 11. 12. 24.]]


In [0]:
new_data=pd.DataFrame(imputed_data,columns=df.columns)

In [21]:
new_data

A     B     C     D
0  10.0  20.0  30.0  40.0
1   1.0   2.0  21.0  24.0
2   5.0   6.0  21.0   8.0
3   0.0  11.0  12.0  24.0

#Handling Categorical Data

In [0]:
df=pd.DataFrame({"Color":["Red","Green","Blue","Red"],
                 "Size":["L","XL","S","M"],
                 "Price":[15.1,20,12.34,13],
                 "Classlabel":["Class1","Class2","Class2","Class1"]
                 })

In [24]:
df

Color Size  Price Classlabel
0    Red    L  15.10     Class1
1  Green   XL  20.00     Class2
2   Blue    S  12.34     Class2
3    Red    M  13.00     Class1

In [0]:
size_map={'S':1,'M':2,'L':3,'XL':4}
df['Size']=df['Size'].map(size_map)

In [28]:
df

Color  Size  Price Classlabel
0    Red     3  15.10     Class1
1  Green     4  20.00     Class2
2   Blue     1  12.34     Class2
3    Red     2  13.00     Class1

In [0]:
Color_map={"Red":0,"Green":1,"Blue":2}
df.Color=df.Color.map(Color_map)

In [30]:
df

Color  Size  Price Classlabel
0      0     3  15.10     Class1
1      1     4  20.00     Class2
2      2     1  12.34     Class2
3      0     2  13.00     Class1

In [31]:
df.Classlabel.unique()

array(['Class1', 'Class2'], dtype=object)

In [0]:
Class_map={"Class1":1,"Class2":2}
df.Classlabel=df.Classlabel.map(Class_map)

In [33]:
df

Color  Size  Price  Classlabel
0      0     3  15.10           1
1      1     4  20.00           2
2      2     1  12.34           2
3      0     2  13.00           1

In [35]:
#Inverse mapping
inv_size={}
for k,v in size_map.items():
  inv_size[v]=k
  print(inv_size)

{1: 'S'}
{1: 'S', 2: 'M'}
{1: 'S', 2: 'M', 3: 'L'}
{1: 'S', 2: 'M', 3: 'L', 4: 'XL'}


In [36]:
inv_size

{1: 'S', 2: 'M', 3: 'L', 4: 'XL'}

In [37]:
df.Size.map(inv_size)

0     L
1    XL
2     S
3     M
Name: Size, dtype: object

In [0]:
#LabelEncoder
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(df['Classlabels'].values)
print(y)
c=le.inverse_transform(y)
print(c)

#One Hot Encoding

In [0]:
df=pd.DataFrame({"Color":["Red","Green","Blue","Red"],
                 "Size":["L","XL","S","M"],
                 "Price":[15.1,20,12.34,13],
                 "Classlabel":["Class1","Class2","Class2","Class1"]
                 })

In [56]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
ohe=OneHotEncoder() # 0 = column number
y=LabelEncoder().fit_transform(df.Color.values).reshape(-1,1)
x=ohe.fit_transform(y).toarray()
print(x)

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


In [0]:
#dummies
df=pd.DataFrame({'Country':['Russia','Germany','Australia','Korea','Germany']})